name: Debian User Terminal
version: 12.5.12.4
slug: deb-user
description: User Termnal for the debian shell.
url: https://github.com/pssc/ha-addon-deb/
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
startup: services
stdin: true
apparmor: false
audio: true
ports:
  22/tcp: null
ports_description:
  22/tcp: SSH Access
timeout: 180
map:
  - homeassistant_config:rw
  - addon_config:rw
  - all_addon_configs:rw
  - ssl
  - share:rw
  - backup:rw
  - media:rw
  - addons:rw
tmpfs: true
docker_api: true
hassio_api: true
hassio_role: manager
udev: true
host_dbus: true
full_access: true
homeassistant_api: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
  - SYS_RAWIO
  - SYS_TIME
  - SYS_NICE
  - SYS_RESOURCE
  - SYS_PTRACE
  - SYS_MODULE
  - DAC_READ_SEARCH
host_network: true
backup_exclude:
  - /data/music
  - /data/mount
  - /data/mnt
  - /data/nobackup
  - /data/force_build
ingress: true
ingress_port: 0
panel_icon: mdi:debian
panel_title: User Terminal
stage: experimental
services:
  - mqtt:want
  - mysql:want
options:
  links: []
  mounts: []
  dirs: []
  init_commands: []
  packages: []
schema:
  ssl: bool?
  certfile: str?
  keyfile: str?
  tmpfs: bool?
  mount: str?
  options: str?
  logdir: str?
  logfile: str?
  prefs: str?
  cache: str?
  plugs: str?
  saved: bool?
  links:
    - link: str
      dest: str
  mounts:
    - str?
  dirs:
    - str?
  init_commands:
    - str?
  packages:
    - str?
image: "ghcr.io/pssc/ha-addon-deb-user-{arch}"

