#!/bin/bash
echo init pid "$$" args "$@"
#clone std in
exec 10<&0
mkdir /haos
mount --rbind /run /haos
mount -t tmpfs -o rw,nosuid,nodev,mode=755 tmpfs /run
mount -o remount,exec /config
#umount /proc/asound
echo s6init next
exec /s6init "$@"
